### ISSUE TITLE
请问什么时候可以提供详细的文档呢

### ISSUE THREAD

**Issue by zuijiaoluo** [arniu/react-native-alipay-sdk#2]
很高兴您能提供此 sdk，但是对于如何使用它现在还没有详细的文档，看到已经有10天了，请问什么时候会有详细的说明文档呢？

**Comment by arniu** [comment]
我们正着手移植，这两天就会发布，敬请期待~

**Comment by github4me** [comment]
请问有进一步的消息么， 给个link呗

**Comment by arniu** [comment]
因为没有测试环境，这个项目已经暂停维护。

非常抱歉～
